RATING_INDEX = 0
SITTER_IMAGE_INDEX = 1
END_DATE_INDEX = 2 
TEXT_INDEX = 3
OWNER_IMAGE_INDEX = 4
DOGS_INDEX = 5 
SITTER_INDEX = 6 
OWNER_INDEX = 7
START_DATE_INDEX = 8
SITTER_PHONE_NUMBER_INDEX = 9
SITTER_EMAIL_INDEX = 10
OWNER_PHONE_NUMBER_INDEX = 11
OWNER_EMAIL_INDEX = 12
RESPONSE_TIME_MINUTES_INDEX = 13
REVIEWS_PATH = r'db\reviews.csv'

